import { LabItem } from '../types';

export interface LabCategoryMeta {
  id: string;
  name: string;
  shortName: string;
  description: string;
  iconName: 'Droplet' | 'Activity' | 'Clock' | 'FlaskConical' | 'ShieldAlert' | 'Microscope' | 'Wind' | 'TestTube2';
  theme: {
    badgeBg: string;
    border: string;
    text: string;
    activeBg: string;
    activeBorder: string;
    activeText: string;
    hoverBg: string;
    accentGlow: string;
    chipBg: string;
    chipText: string;
    chipBorder: string;
  };
  analytes: Array<Omit<LabItem, 'id'> & {
    suggestedValues?: string[];
    normalHint?: string;
  }>;
}

export const LAB_CATEGORIES: LabCategoryMeta[] = [
  {
    id: 'hepatograma',
    name: 'Hepatograma & Función Hepática',
    shortName: 'Hepatograma',
    description: 'Bilirrubinas, transaminasas TGO/TGP, fosfatasa alcalina, albúmina y enzimas hepáticas',
    iconName: 'Activity',
    theme: {
      badgeBg: 'bg-amber-100 text-amber-900 border-amber-300',
      border: 'border-amber-200',
      text: 'text-amber-800',
      activeBg: 'bg-amber-500 text-white',
      activeBorder: 'border-amber-600',
      activeText: 'text-white',
      hoverBg: 'hover:bg-amber-50',
      accentGlow: 'shadow-amber-500/20',
      chipBg: 'bg-amber-50 hover:bg-amber-100',
      chipText: 'text-amber-900',
      chipBorder: 'border-amber-300',
    },
    analytes: [
      { name: 'Bilirrubina Total', unit: 'mg/dL', value: '', category: 'hepatograma', reference: [0.2, 1.2], normalHint: '0.2 - 1.2 mg/dL' },
      { name: 'Bilirrubina Directa', unit: 'mg/dL', value: '', category: 'hepatograma', reference: [0.0, 0.3], normalHint: '0.0 - 0.3 mg/dL' },
      { name: 'Bilirrubina Indirecta', unit: 'mg/dL', value: '', category: 'hepatograma', reference: [0.1, 0.9], normalHint: '0.1 - 0.9 mg/dL' },
      { name: 'TGO / AST', unit: 'U/L', value: '', category: 'hepatograma', reference: [10, 40], normalHint: '10 - 40 U/L' },
      { name: 'TGP / ALT', unit: 'U/L', value: '', category: 'hepatograma', reference: [10, 45], normalHint: '10 - 45 U/L' },
      { name: 'Fosfatasa Alcalina (FAL)', unit: 'U/L', value: '', category: 'hepatograma', reference: [40, 130], normalHint: '40 - 130 U/L' },
      { name: 'GGT (Gamma GT)', unit: 'U/L', value: '', category: 'hepatograma', reference: [8, 60], normalHint: '8 - 60 U/L' },
      { name: 'Proteínas Totales', unit: 'g/dL', value: '', category: 'hepatograma', reference: [6.0, 8.3], normalHint: '6.0 - 8.3 g/dL' },
      { name: 'Albúmina sérica', unit: 'g/dL', value: '', category: 'hepatograma', reference: [3.5, 5.0], normalHint: '3.5 - 5.0 g/dL' },
      { name: 'Colesterol Total', unit: 'mg/dL', value: '', category: 'hepatograma', reference: [120, 200], normalHint: '< 200 mg/dL' },
    ],
  },
  {
    id: 'hematologia',
    name: 'Hematología & Eritrosedimentación',
    shortName: 'Hematología / VSG',
    description: 'Hemograma completo, eritrosedimentación (VSG), PCR, procalcitonina y serie blanca',
    iconName: 'Droplet',
    theme: {
      badgeBg: 'bg-rose-100 text-rose-900 border-rose-300',
      border: 'border-rose-200',
      text: 'text-rose-800',
      activeBg: 'bg-rose-600 text-white',
      activeBorder: 'border-rose-700',
      activeText: 'text-white',
      hoverBg: 'hover:bg-rose-50',
      accentGlow: 'shadow-rose-600/20',
      chipBg: 'bg-rose-50 hover:bg-rose-100',
      chipText: 'text-rose-900',
      chipBorder: 'border-rose-300',
    },
    analytes: [
      { name: 'Eritrosedimentación (VSG 1ª h)', unit: 'mm/h', value: '', category: 'hematologia', reference: [2, 20], normalHint: '2 - 20 mm/h' },
      { name: 'Proteína C Reactiva (PCR)', unit: 'mg/L', value: '', category: 'hematologia', reference: [0, 5], normalHint: '< 5 mg/L' },
      { name: 'Procalcitonina (PCT)', unit: 'ng/mL', value: '', category: 'hematologia', reference: [0.0, 0.5], normalHint: '< 0.5 ng/mL' },
      { name: 'Hemoglobina', unit: 'g/dL', value: '', category: 'hematologia', reference: [12.0, 16.5], normalHint: '12.0 - 16.5 g/dL' },
      { name: 'Hematocrito', unit: '%', value: '', category: 'hematologia', reference: [36, 48], normalHint: '36 - 48 %' },
      { name: 'Leucocitos (GB)', unit: '×10³/µL', value: '', category: 'hematologia', reference: [4.5, 11.0], normalHint: '4.5 - 11.0 ×10³/µL' },
      { name: 'Plaquetas', unit: '×10³/µL', value: '', category: 'hematologia', reference: [150, 450], normalHint: '150 - 450 ×10³/µL' },
      { name: 'Neutrófilos segmentados', unit: '%', value: '', category: 'hematologia', reference: [45, 70], normalHint: '45 - 70 %' },
      { name: 'Linfocitos', unit: '%', value: '', category: 'hematologia', reference: [20, 45], normalHint: '20 - 45 %' },
      { name: 'Ferritina sérica', unit: 'ng/mL', value: '', category: 'hematologia', reference: [20, 250], normalHint: '20 - 250 ng/mL' },
    ],
  },
  {
    id: 'coagulograma',
    name: 'Coagulograma & Hemostasia',
    shortName: 'Coagulograma',
    description: 'Tiempo de protrombina, RIN/INR, KPTT/aPTT, fibrinógeno y dímero D',
    iconName: 'Clock',
    theme: {
      badgeBg: 'bg-purple-100 text-purple-900 border-purple-300',
      border: 'border-purple-200',
      text: 'text-purple-800',
      activeBg: 'bg-purple-600 text-white',
      activeBorder: 'border-purple-700',
      activeText: 'text-white',
      hoverBg: 'hover:bg-purple-50',
      accentGlow: 'shadow-purple-600/20',
      chipBg: 'bg-purple-50 hover:bg-purple-100',
      chipText: 'text-purple-900',
      chipBorder: 'border-purple-300',
    },
    analytes: [
      { name: 'Tiempo de Protrombina (TP %)', unit: '%', value: '', category: 'coagulograma', reference: [70, 100], normalHint: '70 - 100 %' },
      { name: 'RIN / INR', unit: 'ratio', value: '', category: 'coagulograma', reference: [0.8, 1.2], normalHint: '0.8 - 1.2 (ACO: 2.0-3.0)' },
      { name: 'KPTT / aPTT', unit: 'seg', value: '', category: 'coagulograma', reference: [25, 38], normalHint: '25 - 38 seg' },
      { name: 'Fibrinógeno', unit: 'mg/dL', value: '', category: 'coagulograma', reference: [200, 400], normalHint: '200 - 400 mg/dL' },
      { name: 'Dímero D', unit: 'ng/mL', value: '', category: 'coagulograma', reference: [0, 500], normalHint: '< 500 ng/mL' },
      { name: 'Tiempo de Sangría', unit: 'min', value: '', category: 'coagulograma', reference: [1, 4], normalHint: '1 - 4 min' },
    ],
  },
  {
    id: 'quimica',
    name: 'Química Clínica & Medio Interno',
    shortName: 'Química & Iones',
    description: 'Glucemia, función renal (urea/creatinina), electrolitos y estado metabólico',
    iconName: 'FlaskConical',
    theme: {
      badgeBg: 'bg-sky-100 text-sky-900 border-sky-300',
      border: 'border-sky-200',
      text: 'text-sky-800',
      activeBg: 'bg-sky-600 text-white',
      activeBorder: 'border-sky-700',
      activeText: 'text-white',
      hoverBg: 'hover:bg-sky-50',
      accentGlow: 'shadow-sky-600/20',
      chipBg: 'bg-sky-50 hover:bg-sky-100',
      chipText: 'text-sky-900',
      chipBorder: 'border-sky-300',
    },
    analytes: [
      { name: 'Glucemia en ayunas', unit: 'mg/dL', value: '', category: 'quimica', reference: [70, 110], normalHint: '70 - 110 mg/dL' },
      { name: 'Urea', unit: 'mg/dL', value: '', category: 'quimica', reference: [15, 45], normalHint: '15 - 45 mg/dL' },
      { name: 'Creatinina sérica', unit: 'mg/dL', value: '', category: 'quimica', reference: [0.6, 1.3], normalHint: '0.6 - 1.3 mg/dL' },
      { name: 'Sodio (Na+)', unit: 'mEq/L', value: '', category: 'quimica', reference: [135, 145], normalHint: '135 - 145 mEq/L' },
      { name: 'Potasio (K+)', unit: 'mEq/L', value: '', category: 'quimica', reference: [3.5, 5.1], normalHint: '3.5 - 5.1 mEq/L' },
      { name: 'Cloro (Cl-)', unit: 'mEq/L', value: '', category: 'quimica', reference: [96, 106], normalHint: '96 - 106 mEq/L' },
      { name: 'Calcio iónico', unit: 'mg/dL', value: '', category: 'quimica', reference: [4.5, 5.3], normalHint: '4.5 - 5.3 mg/dL' },
      { name: 'Magnesio (Mg)', unit: 'mg/dL', value: '', category: 'quimica', reference: [1.7, 2.5], normalHint: '1.7 - 2.5 mg/dL' },
      { name: 'Ácido Láctico / Lactato', unit: 'mmol/L', value: '', category: 'quimica', reference: [0.5, 2.2], normalHint: '0.5 - 2.2 mmol/L' },
      { name: 'Ácido Úrico', unit: 'mg/dL', value: '', category: 'quimica', reference: [3.0, 7.0], normalHint: '3.0 - 7.0 mg/dL' },
    ],
  },
  {
    id: 'serologia',
    name: 'Serología & Inmunología',
    shortName: 'Serología',
    description: 'VIH, hepatitis virales B/C, VDRL sífilis, Chagas y anticuerpos infecciosos',
    iconName: 'ShieldAlert',
    theme: {
      badgeBg: 'bg-pink-100 text-pink-900 border-pink-300',
      border: 'border-pink-200',
      text: 'text-pink-800',
      activeBg: 'bg-pink-600 text-white',
      activeBorder: 'border-pink-700',
      activeText: 'text-white',
      hoverBg: 'hover:bg-pink-50',
      accentGlow: 'shadow-pink-600/20',
      chipBg: 'bg-pink-50 hover:bg-pink-100',
      chipText: 'text-pink-900',
      chipBorder: 'border-pink-300',
    },
    analytes: [
      {
        name: 'VIH (Ag p24 / Ac)',
        unit: 'Cualitativo',
        value: '',
        category: 'serologia',
        isQualitative: true,
        suggestedValues: ['No reactivo', 'Reactivo', 'Indeterminado'],
        normalHint: 'No reactivo',
      },
      {
        name: 'Hepatitis B (HBsAg)',
        unit: 'Cualitativo',
        value: '',
        category: 'serologia',
        isQualitative: true,
        suggestedValues: ['No reactivo', 'Reactivo'],
        normalHint: 'No reactivo',
      },
      {
        name: 'Hepatitis C (Anti-HCV)',
        unit: 'Cualitativo',
        value: '',
        category: 'serologia',
        isQualitative: true,
        suggestedValues: ['No reactivo', 'Reactivo'],
        normalHint: 'No reactivo',
      },
      {
        name: 'VDRL / Sífilis',
        unit: 'Cualitativo',
        value: '',
        category: 'serologia',
        isQualitative: true,
        suggestedValues: ['No reactivo', 'Reactivo 1:2', 'Reactivo 1:8', 'Reactivo 1:16', 'Reactivo 1:32'],
        normalHint: 'No reactivo',
      },
      {
        name: 'Serología Chagas (HAI/ELISA)',
        unit: 'Cualitativo',
        value: '',
        category: 'serologia',
        isQualitative: true,
        suggestedValues: ['No reactivo', 'Reactivo'],
        normalHint: 'No reactivo',
      },
      {
        name: 'Dengue (NS1 / IgM / IgG)',
        unit: 'Cualitativo',
        value: '',
        category: 'serologia',
        isQualitative: true,
        suggestedValues: ['Negativo', 'Positivo NS1 (Agudo)', 'Positivo IgM', 'Positivo IgG'],
        normalHint: 'Negativo',
      },
      {
        name: 'Test Antígeno Respiratorio',
        unit: 'Cualitativo',
        value: '',
        category: 'serologia',
        isQualitative: true,
        suggestedValues: ['Negativo', 'Positivo COVID-19', 'Positivo Influenza A', 'Positivo Influenza B'],
        normalHint: 'Negativo',
      },
    ],
  },
  {
    id: 'cultivos',
    name: 'Cultivos & Microbiología',
    shortName: 'Cultivos',
    description: 'Urocultivos, hemocultivos x2, esputo, hisopados, heridas y antibiogramas',
    iconName: 'Microscope',
    theme: {
      badgeBg: 'bg-emerald-100 text-emerald-900 border-emerald-300',
      border: 'border-emerald-200',
      text: 'text-emerald-800',
      activeBg: 'bg-emerald-600 text-white',
      activeBorder: 'border-emerald-700',
      activeText: 'text-white',
      hoverBg: 'hover:bg-emerald-50',
      accentGlow: 'shadow-emerald-600/20',
      chipBg: 'bg-emerald-50 hover:bg-emerald-100',
      chipText: 'text-emerald-900',
      chipBorder: 'border-emerald-300',
    },
    analytes: [
      {
        name: 'Urocultivo',
        unit: 'Microbiología',
        value: '',
        category: 'cultivos',
        isQualitative: true,
        suggestedValues: ['Sin desarrollo a las 48h', 'En incubación (24-48h)', 'Positivo: E. coli >100.000 UFC/ml', 'Positivo: Klebsiella pneumoniae'],
        normalHint: 'Sin desarrollo',
      },
      {
        name: 'Hemocultivos (1/2 y 2/2)',
        unit: 'Microbiología',
        value: '',
        category: 'cultivos',
        isQualitative: true,
        suggestedValues: ['En incubación', 'Negativos a las 48h', 'Negativos definitivos a 5 días', 'Positivo frasco 1: Cocos Gram (+)'],
        normalHint: 'Negativos',
      },
      {
        name: 'Cultivo de Esputo / Traqueal',
        unit: 'Microbiología',
        value: '',
        category: 'cultivos',
        isQualitative: true,
        suggestedValues: ['Flora habitual saprófita', 'Sin desarrollo', 'Positivo: Pseudomonas aeruginosa', 'Positivo: Streptococcus pneumoniae'],
        normalHint: 'Flora saprófita',
      },
      {
        name: 'Cultivo de Herida / Secreción',
        unit: 'Microbiología',
        value: '',
        category: 'cultivos',
        isQualitative: true,
        suggestedValues: ['Sin desarrollo bacteriano', 'Positivo: Staphylococcus aureus', 'Positivo: SAMR'],
        normalHint: 'Sin desarrollo',
      },
      {
        name: 'Hisopado / PCR Viral',
        unit: 'Microbiología',
        value: '',
        category: 'cultivos',
        isQualitative: true,
        suggestedValues: ['Negativo para virus respiratorios', 'Positivo: Virus Sincicial Respiratorio', 'Positivo: SARS-CoV-2'],
        normalHint: 'Negativo',
      },
      {
        name: 'Antibiograma / Sensibilidad',
        unit: 'Informe',
        value: '',
        category: 'cultivos',
        isQualitative: true,
        suggestedValues: ['Sensible: TMS, Ciprofloxacino | Resistente: Cefalotina', 'Sensible: Amikacina, Meropenem', 'BLEE Positivo'],
        normalHint: 'Ver informe',
      },
    ],
  },
  {
    id: 'gases',
    name: 'Gases Arteriales (EAB) & Marcadores',
    shortName: 'Gases (EAB)',
    description: 'Equilibrio ácido-base (pH, pO2, pCO2, HCO3, EB) y troponinas/enzimas',
    iconName: 'Wind',
    theme: {
      badgeBg: 'bg-indigo-100 text-indigo-900 border-indigo-300',
      border: 'border-indigo-200',
      text: 'text-indigo-800',
      activeBg: 'bg-indigo-600 text-white',
      activeBorder: 'border-indigo-700',
      activeText: 'text-white',
      hoverBg: 'hover:bg-indigo-50',
      accentGlow: 'shadow-indigo-600/20',
      chipBg: 'bg-indigo-50 hover:bg-indigo-100',
      chipText: 'text-indigo-900',
      chipBorder: 'border-indigo-300',
    },
    analytes: [
      { name: 'pH arterial', unit: 'unid', value: '', category: 'gases', reference: [7.35, 7.45], normalHint: '7.35 - 7.45' },
      { name: 'pO2 arterial', unit: 'mmHg', value: '', category: 'gases', reference: [80, 100], normalHint: '80 - 100 mmHg' },
      { name: 'pCO2 arterial', unit: 'mmHg', value: '', category: 'gases', reference: [35, 45], normalHint: '35 - 45 mmHg' },
      { name: 'HCO3- (Bicarbonato)', unit: 'mEq/L', value: '', category: 'gases', reference: [22, 26], normalHint: '22 - 26 mEq/L' },
      { name: 'Exceso de Bases (EB)', unit: 'mEq/L', value: '', category: 'gases', reference: [-2, 2], normalHint: '-2 a +2 mEq/L' },
      { name: 'Troponina I ultrasensible', unit: 'ng/L', value: '', category: 'gases', reference: [0, 14], normalHint: '< 14 ng/L' },
      { name: 'CPK total', unit: 'U/L', value: '', category: 'gases', reference: [24, 195], normalHint: '24 - 195 U/L' },
      { name: 'Pro-BNP', unit: 'pg/mL', value: '', category: 'gases', reference: [0, 300], normalHint: '< 300 pg/mL' },
    ],
  },
  {
    id: 'orina',
    name: 'Orina Completa & Sedimento',
    shortName: 'Orina Completa',
    description: 'Físico-químico de orina, densidad, pH, proteinuria, glucosuria y sedimento',
    iconName: 'TestTube2',
    theme: {
      badgeBg: 'bg-yellow-100 text-yellow-900 border-yellow-300',
      border: 'border-yellow-200',
      text: 'text-yellow-800',
      activeBg: 'bg-yellow-600 text-white',
      activeBorder: 'border-yellow-700',
      activeText: 'text-white',
      hoverBg: 'hover:bg-yellow-50',
      accentGlow: 'shadow-yellow-600/20',
      chipBg: 'bg-yellow-50 hover:bg-yellow-100',
      chipText: 'text-yellow-900',
      chipBorder: 'border-yellow-300',
    },
    analytes: [
      { name: 'Densidad urinaria', unit: 'densidad', value: '', category: 'orina', reference: [1.010, 1.025], normalHint: '1.010 - 1.025' },
      { name: 'pH urinario', unit: 'pH', value: '', category: 'orina', reference: [5.0, 7.0], normalHint: '5.0 - 7.0' },
      {
        name: 'Proteínas en orina',
        unit: 'Cualitativo',
        value: '',
        category: 'orina',
        isQualitative: true,
        suggestedValues: ['Negativo', 'Trazas', '1+ (30 mg/dL)', '2+ (100 mg/dL)', '3+ (300 mg/dL)'],
        normalHint: 'Negativo',
      },
      {
        name: 'Glucosa en orina',
        unit: 'Cualitativo',
        value: '',
        category: 'orina',
        isQualitative: true,
        suggestedValues: ['Negativo / Normal', 'Positivo (+)'],
        normalHint: 'Negativo',
      },
      {
        name: 'Cuerpos Cetónicos',
        unit: 'Cualitativo',
        value: '',
        category: 'orina',
        isQualitative: true,
        suggestedValues: ['Negativo', 'Positivo (+)'],
        normalHint: 'Negativo',
      },
      {
        name: 'Sedimento Urinario',
        unit: 'Microscopía',
        value: '',
        category: 'orina',
        isQualitative: true,
        suggestedValues: ['Leucocitos 0-2 x campo, escasas células', 'Leucocituria abundante y piocitos', 'Hematíes 10-15 x campo (microhematuria)'],
        normalHint: 'Normal',
      },
    ],
  },
];

export const ALL_LAB_PRESETS = LAB_CATEGORIES.flatMap((c) => c.analytes);
