import { AgeGroupKey, AgeGroupRange, LabItem, PatientRecord } from '../types';

export const AGE_GROUP_RANGES: Record<AgeGroupKey, AgeGroupRange> = {
  neonato: {
    label: 'Neonato',
    sublabel: '0–28 días',
    fc: [100, 180],
    fr: [30, 60],
    tas: [60, 90],
    tad: [30, 60],
    temp: [36.5, 37.5],
    spo2: 95,
  },
  lactante: {
    label: 'Lactante',
    sublabel: '1–12 meses',
    fc: [100, 160],
    fr: [30, 50],
    tas: [70, 100],
    tad: [50, 65],
    temp: [36.5, 37.5],
    spo2: 95,
  },
  preescolar: {
    label: 'Preescolar',
    sublabel: '1–5 años',
    fc: [90, 140],
    fr: [20, 30],
    tas: [80, 110],
    tad: [50, 70],
    temp: [36.0, 37.5],
    spo2: 95,
  },
  escolar: {
    label: 'Escolar',
    sublabel: '6–12 años',
    fc: [70, 120],
    fr: [18, 25],
    tas: [90, 110],
    tad: [55, 75],
    temp: [36.0, 37.5],
    spo2: 95,
  },
  adolescente: {
    label: 'Adolescente',
    sublabel: '12–18 años',
    fc: [60, 100],
    fr: [12, 20],
    tas: [90, 120],
    tad: [60, 80],
    temp: [36.0, 37.5],
    spo2: 95,
  },
  adulto: {
    label: 'Adulto',
    sublabel: '18–64 años',
    fc: [60, 100],
    fr: [12, 20],
    tas: [90, 140],
    tad: [60, 90],
    temp: [36.0, 37.5],
    spo2: 95,
  },
  adulto_mayor: {
    label: 'Adulto mayor',
    sublabel: '≥65 años',
    fc: [60, 100],
    fr: [12, 24],
    tas: [90, 150],
    tad: [60, 90],
    temp: [35.8, 37.2],
    spo2: 94,
  },
};

export const DEFAULT_LAB_PRESETS: Omit<LabItem, 'id'>[] = [
  { name: 'Hemoglobina', unit: 'g/dL', value: '', reference: [12.0, 16.5] },
  { name: 'Leucocitos', unit: '×10³/µL', value: '', reference: [4.5, 11.0] },
  { name: 'Plaquetas', unit: '×10³/µL', value: '', reference: [150, 450] },
  { name: 'Glucemia en ayunas', unit: 'mg/dL', value: '', reference: [70, 110] },
  { name: 'Creatinina sérica', unit: 'mg/dL', value: '', reference: [0.6, 1.3] },
  { name: 'Urea', unit: 'mg/dL', value: '', reference: [15, 45] },
  { name: 'Sodio (Na+)', unit: 'mEq/L', value: '', reference: [135, 145] },
  { name: 'Potasio (K+)', unit: 'mEq/L', value: '', reference: [3.5, 5.1] },
];

export const GLASGOW_OPTIONS = {
  ocular: [
    { value: 4, label: '4 - Espontánea', desc: 'Abre ojos sin estímulo' },
    { value: 3, label: '3 - A la orden verbal', desc: 'Abre ojos al hablarle' },
    { value: 2, label: '2 - Al dolor', desc: 'Abre ojos al estímulo doloroso' },
    { value: 1, label: '1 - Sin respuesta', desc: 'No abre los ojos' },
  ],
  verbal: [
    { value: 5, label: '5 - Orientado', desc: 'Orientado en tiempo, espacio y persona' },
    { value: 4, label: '4 - Confuso', desc: 'Conversa pero desorientado' },
    { value: 3, label: '3 - Palabras inapropiadas', desc: 'Frases o palabras sueltas' },
    { value: 2, label: '2 - Sonidos incomprensibles', desc: 'Quejidos o gemidos' },
    { value: 1, label: '1 - Sin respuesta', desc: 'No emite sonidos' },
  ],
  motor: [
    { value: 6, label: '6 - Obedece órdenes', desc: 'Sigue instrucciones sencillas' },
    { value: 5, label: '5 - Localiza el dolor', desc: 'Intenta retirar o señalar estímulo' },
    { value: 4, label: '4 - Retirada al dolor', desc: 'Flexión normal de retirada' },
    { value: 3, label: '3 - Flexión anormal', desc: 'Rigidez de decorticación' },
    { value: 2, label: '2 - Extensión anormal', desc: 'Rigidez de descerebración' },
    { value: 1, label: '1 - Sin respuesta', desc: 'Flacidez total' },
  ],
};

export const BRADEN_CRITERIA = {
  percepcion: [
    { value: 1, label: '1 - Completamente limitada', desc: 'No responde a estímulos dolorosos' },
    { value: 2, label: '2 - Muy limitada', desc: 'Responde solo a estímulos dolorosos' },
    { value: 3, label: '3 - Ligeramente limitada', desc: 'Responde a órdenes verbales, dificultad leve' },
    { value: 4, label: '4 - Sin limitaciones', desc: 'Responde a órdenes verbales con normalidad' },
  ],
  humedad: [
    { value: 1, label: '1 - Constantemente húmeda', desc: 'Piel constantemente expuesta a sudor, orina' },
    { value: 2, label: '2 - A menudo húmeda', desc: 'Cambios de lencería al menos 3 veces por turno' },
    { value: 3, label: '3 - Ocasionalmente húmeda', desc: 'Requiere cambio de lencería 1 vez al día' },
    { value: 4, label: '4 - Raramente húmeda', desc: 'Piel habitualmente seca' },
  ],
  actividad: [
    { value: 1, label: '1 - Encamado', desc: 'Confinado a la cama' },
    { value: 2, label: '2 - En silla', desc: 'Capacidad muy limitada para caminar, casi en silla' },
    { value: 3, label: '3 - Camina ocasionalmente', desc: 'Camina distancias cortas con o sin ayuda' },
    { value: 4, label: '4 - Camina frecuentemente', desc: 'Camina fuera de la habitación habitualmente' },
  ],
  movilidad: [
    { value: 1, label: '1 - Completamente inmóvil', desc: 'No realiza cambios de posición corporales' },
    { value: 2, label: '2 - Muy limitada', desc: 'Ocasionalmente ligeros cambios en posición de extremidades' },
    { value: 3, label: '3 - Ligeramente limitada', desc: 'Efectúa con frecuencia cambios posturales leves' },
    { value: 4, label: '4 - Sin limitaciones', desc: 'Realiza cambios posturales importantes de forma autónoma' },
  ],
  nutricion: [
    { value: 1, label: '1 - Muy pobre', desc: 'Nunca ingiere una comida completa, ingesta <1/3' },
    { value: 2, label: '2 - Probablemente inadecuada', desc: 'Raras veces come comida completa, toma ~1/2 de dieta' },
    { value: 3, label: '3 - Adecuada', desc: 'Toma más de la mitad de la mayoría de las comidas' },
    { value: 4, label: '4 - Excelente', desc: 'Come la mayor parte de cada comida' },
  ],
  friccion: [
    { value: 1, label: '1 - Problema', desc: 'Requiere asistencia de moderada a máxima para movilizarse' },
    { value: 2, label: '2 - Problema potencial', desc: 'Se mueve débilmente o requiere mínima asistencia' },
    { value: 3, label: '3 - No existe problema aparente', desc: 'Se mueve en la cama y silla con suficiente fuerza' },
  ],
};

export const createEmptyPatient = (customBed?: string): PatientRecord => {
  const now = new Date();
  return {
    id: `paciente_${Date.now()}_${Math.random().toString(36).substring(2, 6)}`,
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
    nurseName: 'Lic. Enfermería',
    shift: 'Mañana',
    nombre: '',
    cama: customBed || '',
    historiaClinica: '',
    edad: '',
    unidadEdad: 'anios',
    sexo: 'F',
    grupoEtario: 'adulto',
    peso: '',
    talla: '',
    dx: '',
    alergias: 'Ninguna conocida (NKDA)',
    aislamiento: 'Ninguno',
    v_fc: '',
    v_fr: '',
    v_tas: '',
    v_tad: '',
    v_temp: '',
    v_spo2: '',
    n_conciencia: 'Alerta',
    n_go: 4,
    n_gv: 5,
    n_gm: 6,
    n_pupilas: 'Isocóricas',
    n_reactivas: 'Sí',
    n_obs: 'Paciente lúcido, colaborador.',
    r_patron: 'Eupneico',
    r_ruidos: 'Normales',
    r_o2: 'No',
    r_o2det: '',
    r_tos: 'No refiere',
    c_ritmo: 'Regular',
    c_pulsos: 'Presentes / simétricos',
    c_relleno: '< 2 s',
    c_edemas: 'No',
    c_perfusion: 'Rosada, tibia, sin cianosis',
    b_vo: '',
    b_iv: '',
    b_otrosIn: '',
    b_diuresis: '',
    b_drenajes: '',
    b_otrosOut: '',
    u_diuresis: '',
    u_sonda: 'No',
    u_caract: 'Clara, normocoloreada',
    nu_dieta: 'General completa',
    nu_via: 'Oral',
    nu_tolerancia: 'Buena',
    nu_apetito: 'Conservado',
    d_eva: 0,
    d_loc: '',
    d_tipo: 'Sin dolor',
    d_tto: 'No requiere',
    pi_integridad: 'Íntegra',
    pi_loc: '',
    br_1: 4,
    br_2: 4,
    br_3: 4,
    br_4: 4,
    br_5: 4,
    br_6: 3,
    m_nivel: 'Independiente',
    m_disp: 'Ninguno',
    dt_1: false,
    dt_2: false,
    dt_3: false,
    dt_4: false,
    dt_5: false,
    meds: [
      { id: 'med_1', name: 'Paracetamol', dose: '1 g', route: 'VO', time: '08:00', given: true, notes: 'Regulado por dolor/fiebre' }
    ],
    labs: [
      { id: 'lab_1', name: 'Hemoglobina', unit: 'g/dL', value: '13.5', reference: [12.0, 16.5], flag: 'ok' },
      { id: 'lab_2', name: 'Leucocitos', unit: '×10³/µL', value: '7.8', reference: [4.5, 11.0], flag: 'ok' },
      { id: 'lab_3', name: 'Glucemia', unit: 'mg/dL', value: '94', reference: [70, 110], flag: 'ok' },
    ],
    ev_nota: 'Paciente descansando tranquilamente en su unidad. Signos vitales dentro de parámetros normales. Refiere sentirse confortable y sin dolor.',
    pendientes: 'Control de diuresis del turno y pase de guardia a las 14:00.',
  };
};

export const INITIAL_SAMPLE_PATIENT: PatientRecord = {
  id: 'paciente_sample_demo',
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  nurseName: 'Lic. Laura Benítez',
  shift: 'Mañana',
  nombre: 'Carlos Mendoza',
  cama: 'Cama 204-A',
  historiaClinica: 'HC-84291',
  edad: 58,
  unidadEdad: 'anios',
  sexo: 'M',
  grupoEtario: 'adulto',
  peso: 76.5,
  talla: 174,
  dx: 'Neumonía adquirida en la comunidad (NAC) - Día 2 de antibiótico EV',
  alergias: 'Penicilina (urticaria / angioedema)',
  aislamiento: 'Gotitas',
  v_fc: 82,
  v_fr: 19,
  v_tas: 125,
  v_tad: 78,
  v_temp: 37.1,
  v_spo2: 96,
  n_conciencia: 'Alerta',
  n_go: 4,
  n_gv: 5,
  n_gm: 6,
  n_pupilas: 'Isocóricas',
  n_reactivas: 'Sí',
  n_obs: 'Consciente, orientado en tiempo, espacio y persona. Colaborador.',
  r_patron: 'Eupneico',
  r_ruidos: 'Crepitantes',
  r_o2: 'Sí',
  r_o2det: 'Cánula nasal a 2 L/min',
  r_tos: 'Tos productiva moderada con expectoración blanquecina',
  c_ritmo: 'Regular',
  c_pulsos: 'Presentes / simétricos',
  c_relleno: '< 2 s',
  c_edemas: 'No',
  c_perfusion: 'Normocoloreada, tibia, llenado capilar conservado',
  b_vo: 600,
  b_iv: 1000,
  b_otrosIn: 0,
  b_diuresis: 1100,
  b_drenajes: 0,
  b_otrosOut: 200,
  u_diuresis: '1100 ml en 12 h (~91 ml/h)',
  u_sonda: 'No',
  u_caract: 'Clara, ámbar, sin sedimentos ni hematuria',
  nu_dieta: 'Blanda para patología respiratoria, hiposódica',
  nu_via: 'Oral',
  nu_tolerancia: 'Buena',
  nu_apetito: 'Conservado',
  d_eva: 2,
  d_loc: 'Tórax derecho con accesos de tos',
  d_tipo: 'Punzante',
  d_tto: 'Paracetamol 1g EV reglado cada 8h',
  pi_integridad: 'Íntegra',
  pi_loc: 'Sin lesiones por presión observadas en sacro ni talones',
  br_1: 4,
  br_2: 4,
  br_3: 3,
  br_4: 4,
  br_5: 3,
  br_6: 3,
  m_nivel: 'Requiere ayuda parcial',
  m_disp: 'Acompañamiento para deambular al baño',
  dt_1: false,
  dt_2: true,
  dt_3: false,
  dt_4: false,
  dt_5: true,
  meds: [
    { id: 'm1', name: 'Levofloxacino', dose: '500 mg EV', route: 'EV', time: '08:00', given: true, notes: 'Infusión en 60 min completada' },
    { id: 'm2', name: 'Salbutamol aerocámara', dose: '2 puffs', route: 'Inhalatoria', time: '09:00', given: true, notes: 'Buena respuesta broncodilatadora' },
    { id: 'm3', name: 'Solución Fisiológica 0.9%', dose: '1000 ml', route: 'EV', time: '14:00', given: false, notes: 'Goteo continuo 42 ml/h' },
  ],
  labs: [
    { id: 'l1', name: 'Hemoglobina', unit: 'g/dL', value: '13.8', category: 'hematologia', reference: [12.0, 16.5], flag: 'ok' },
    { id: 'l2', name: 'Leucocitos (GB)', unit: '×10³/µL', value: '11.4', category: 'hematologia', reference: [4.5, 11.0], flag: 'high' },
    { id: 'l3', name: 'Eritrosedimentación (VSG 1ª h)', unit: 'mm/h', value: '38', category: 'hematologia', reference: [2, 20], flag: 'high' },
    { id: 'l4', name: 'Glucemia en ayunas', unit: 'mg/dL', value: '102', category: 'quimica', reference: [70, 110], flag: 'ok' },
    { id: 'l5', name: 'Creatinina sérica', unit: 'mg/dL', value: '0.9', category: 'quimica', reference: [0.6, 1.3], flag: 'ok' },
    { id: 'l6', name: 'TGP / ALT', unit: 'U/L', value: '28', category: 'hepatograma', reference: [10, 45], flag: 'ok' },
    { id: 'l7', name: 'RIN / INR', unit: 'ratio', value: '1.05', category: 'coagulograma', reference: [0.8, 1.2], flag: 'ok' },
    { id: 'l8', name: 'Urocultivo', unit: 'Microbiología', value: 'Sin desarrollo a las 48h', category: 'cultivos', isQualitative: true, flag: 'ok' },
    { id: 'l9', name: 'VIH (Ag p24 / Ac)', unit: 'Cualitativo', value: 'No reactivo', category: 'serologia', isQualitative: true, flag: 'ok' },
  ],
  ev_nota: 'Paciente hemodinámicamente estable durante el turno. Buena respuesta al tratamiento antibiótico. Ventila con cánula nasal a 2 L/min manteniendo saturaciones de 96%. Afebril. Buen patrón miccional y diuresis espontánea. Tolera dieta oral asignada.',
  pendientes: '• Control de temperatura a las 16:00 hs.\n• Infusión de hidratación parenteral en curso a 42 ml/h.\n• Pendiente control radiológico de tórax ambulatorio si persiste mejoría.',
};
